export const options = [
  {
    id: "markdown",
    label: "Markdown",
    description: "## file.py \n\n```\ncode\n```",
  },
  {
    id: "xml",
    label: "XML",
    description: "<name>\n  file.py\n</name>\n<code>\n  code\n</code>",
  },
];

export const markdownOptions = [
  {
    id: "markdown1",
    label: "Headings + Code Blocks",
    description: "## name \n\n```\ncontent\n```",
  },
  {
    id: "markdown2",
    label: "Headings",
    description: "## name \n\ncontent",
  },
];

export const xmlOptions = [
  {
    id: "xml1",
    label: "Option 1",
    description: '<file name="name">content</file>',
  },
  {
    id: "xml2",
    label: "Option 2",
    description:
      "<file>\n  <name>name</name>\n  <content>content</content>\n</file>",
  },
];

export const acceptedFileTypes = [
  "text/*",
  "application/json",
  "application/javascript",
  "application/typescript",
  "application/xml",
  "application/x-yaml",
  "application/yaml",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/zip",
  // Common text file extensions
  ".txt",
  ".md",
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".json",
  ".xml",
  ".html",
  ".htm",
  ".css",
  ".scss",
  ".sass",
  ".less",
  ".py",
  ".java",
  ".c",
  ".cpp",
  ".h",
  ".hpp",
  ".cs",
  ".php",
  ".rb",
  ".go",
  ".rs",
  ".swift",
  ".kt",
  ".scala",
  ".sh",
  ".bash",
  ".zsh",
  ".fish",
  ".ps1",
  ".bat",
  ".cmd",
  ".sql",
  ".r",
  ".m",
  ".pl",
  ".lua",
  ".vim",
  ".dockerfile",
  ".gitignore",
  ".env",
  ".ini",
  ".cfg",
  ".conf",
  ".config",
  ".toml",
  ".yaml",
  ".yml",
  ".log",
  ".csv",
  ".tsv",
  ".rtf",
];

// Maximum file sizes
export const MAX_REGULAR_FILE_SIZE = 5 * 1024 * 1024; // 5MB for regular text files
export const MAX_ZIP_FILE_SIZE = 50 * 1024 * 1024; // 50MB for ZIP files

export const ACCEPTED_TEXT_TYPES = [
  "text/",
  "application/json",
  "application/javascript",
  "application/typescript",
  "application/xml",
  "application/x-yaml",
  "application/yaml",
];

export const ACCEPTED_FILE_EXTENSIONS = [
  ".txt",
  ".md",
  ".markdown",
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".json",
  ".xml",
  ".html",
  ".htm",
  ".css",
  ".scss",
  ".sass",
  ".less",
  ".py",
  ".java",
  ".c",
  ".cpp",
  ".h",
  ".hpp",
  ".cs",
  ".php",
  ".rb",
  ".go",
  ".rs",
  ".swift",
  ".kt",
  ".scala",
  ".sh",
  ".bash",
  ".zsh",
  ".fish",
  ".ps1",
  ".bat",
  ".cmd",
  ".sql",
  ".r",
  ".m",
  ".pl",
  ".lua",
  ".vim",
  ".dockerfile",
  ".gitignore",
  ".env",
  ".ini",
  ".cfg",
  ".conf",
  ".config",
  ".toml",
  ".yaml",
  ".yml",
  ".log",
  ".csv",
  ".tsv",
  ".rtf",
  ".tex",
  ".latex",
  ".bib",
  ".org",
  ".rst",
  ".adoc",
];
